### ISSUE TITLE
Ansible integration test sometimes ( for cjh1) will not complete successfully

### ISSUE THREAD

**Issue by cjh1** [Kitware/cumulus#165]
I either get an "error" state ( the termination times out ) or it gets stuck in the "terminating" state.

**Comment by kotfic** [comment]
@cjh1  See: https://github.com/ansible/ansible-modules-core/pull/4012

**Comment by cjh1** [comment]
Awesome!

**Comment by kotfic** [comment]
@opadron you may also be interested in the above PR to ansible-modules-core.  Cheers!

**Comment by opadron** [comment]
@kotfic, I'd hug you if I could! ^_^
I can't wait to see that annoying bug squashed!

**Comment by cjh1** [comment]
This fix has been upstreamed, need to wait it to appear in a release.
