### ISSUE TITLE
The ssh endpoint should move from /user to /cluster

### ISSUE THREAD

**Issue by cjh1** [Kitware/cumulus#22]
/user/{id}/ssh/passphrase => /cluster/{id}/ssh/passphrase 
/user/{id}/ssh/publickey => /cluster/{id}/ssh/publickey

**Comment by cjh1** [comment]
or many be ...

GET /cluster/{id}/ssh/passphrase 
GET /cluster/{id}/ssh/publickey

PATCH /cluster/{id}/ssh

**Comment by jourdain** [comment]
I trust your judgment on that, but you right it kind of make sense to have

/user/{id}/{type}/passphrase

**Comment by cjh1** [comment]
The reason for this change is the key is generated for access to a particular cluster, so it makes more sense to associate it with the cluster endpoint.

**Comment by jourdain** [comment]
ok
