### ISSUE TITLE
Look at using tags to fetch AMI ids

### ISSUE THREAD

**Issue by cjh1** [Kitware/cumulus#221]

**Comment by cjh1** [comment]
#244 adds the ability to look up a ami id using a name. This give us away of fetching a consistent ami across regions if we use the same name for the ami across regions.

**Comment by kotfic** [comment]
+1000

On Fri, Jul 8, 2016 at 4:27 PM, Chris Harris <notifications@github.com>
wrote:

> #244 <https://github.com/Kitware/cumulus/pull/244> adds the ability to
> look up a ami id using a name. This give us away of fetching a consistent
> ami across regions if we use the same name for the ami across regions.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kitware/cumulus/issues/221#issuecomment-231464245>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAo5B_nxIlI30YtV1F_2yKYiEJDkidWlks5qTrLPgaJpZM4Ibb2i>
> .
>



-- 
Christopher Kotfila
R&D Engineer
Kitware Inc.
http://www.kitware.com/company/team/kotfila.html

**Comment by cjh1** [comment]
This is fixed in master
