### ISSUE TITLE
Create NWChem taskflow

### ISSUE THREAD

**Issue by cjh1** [Kitware/cumulus#258]
Create NWChem taskflow to support Kitware/HPCCloud#434

**Comment by cjh1** [comment]
[ ] Install nwchem on a trad dev cluster. ( I have installed on ulmus for testing )
[ ] Develop taskflow to perform the following steps ( we can use the [PyFR taskflow](https://github.com/Kitware/HPCCloud/blob/master/server/taskflows/hpccloud/taskflow/pyfr.py) as a template
  1. Download geometry file from Girder to the cluster ( the client should pass the file id and file type )
  2. Download the ini file from Girder to the cluster ( this will be generated SimPut or uploaded by the user ) ( the client should pass the file id to the flow )
  3. Generate/template an appropriate submission script for NWChem using this input files. 
  4. Create and submit job to cluster
  5. Monitor and wait for completion
  6. Upload output to Girder ( assuming output is small )

[NWChem Documentation](http://www.nwchem-sw.org/index.php/Release66:NWChem_Documentation)

**Comment by cjh1** [comment]
@chetnieter This is the next thing I would like you to take a look at. When you are ready to start ping me and I can outline what is required.

**Comment by chetnieter** [comment]
@cjh1 I am ready get started on this. Do we want to do a Hangout tomorrow morning to talk about it? 10 am?

**Comment by cjh1** [comment]
Sure, sounds good.

Chris

**Comment by jourdain** [comment]
@cjh1, let me know if you need me to join. I'm usually here around 8:30 which is 10:30 for you.

**Comment by cjh1** [comment]
@jourdain @TristanWright has made a start on the client side, so we will be mainly looking at the server side, but you are welcome to join.

**Comment by jourdain** [comment]
Ok sounds good, I wasn't sure which side you were thinking.
I'll let you two handle it then... Let me know if you want me to join later in the process for the client side aspect.

**Comment by cjh1** [comment]
Thanks, will do eventually, we are going to look at using vtk.js for some of the viz.

**Comment by jourdain** [comment]
Hum, are you generating some vtkPolyData? As we can not render anything else right now.

**Comment by cjh1** [comment]
We aren't generating anything yet, our first step will be to reuse some work from the OpenChemistry project ( WebGL rendering ). This is down the line ...

**Comment by chetnieter** [comment]
Moved to kitware/hpccloud#504
