### ISSUE TITLE
Convert ParaView taskflow to use pvserver and MPI

### ISSUE THREAD

**Issue by cjh1** [Kitware/cumulus#270]
Here is the submission script that we used in the past for [pvserver](https://github.com/Kitware/cumulus/blob/master/scripts/codes/pvserver.sh) and the corresponding [pvpython script](https://github.com/Kitware/cumulus/blob/master/scripts/codes/pvw.sh) they will be a little out of date but are a start. 

There is some strange handshaking in order to pass the rc port via a file between the two scripts, if you can think of a better strategy that would be great.

**Comment by jourdain** [comment]
If Utkarsh (or someone else) fix the pvbatch interactor initialization issue, then that will be the simpler solution as you would just run something like:

```$ mpi pvbatch pv_web_visualizer.py```

**Comment by cjh1** [comment]
How does that solution work?

**Comment by jourdain** [comment]
pvbatch as opposed to pvpython handle internally the mpi process distribution. Basically any process != 0 will act like a pvserver satellite process. While the root node will act as both the root node of pvserver and the client.

**Comment by jourdain** [comment]
pvpython can only be a client process, so if you were running it with mpi, you will multiply the clients, which doesn't work.

You can see pvbatch as a (pvserver+client).

**Comment by chetnieter** [comment]
So I just noticed that this issue is for cumulus but the current paraview taskflow lives in HPCCloud. Does this mean that we want to move the paraview taskflow to cumulus to make it available to other projects if needed?

**Comment by cjh1** [comment]
No, I just raise the issue on the wrong repo. can you move it over?

**Comment by chetnieter** [comment]
Moved to kitware/hpccloud#502.
