### ISSUE TITLE
Take a look at Deltacloud

### ISSUE THREAD

**Issue by cjh1** [Kitware/cumulus#30]
This looks worth taking a look at:

https://deltacloud.apache.org/rest-api.html

**Comment by jourdain** [comment]
indeed...

**Comment by patrickoleary** [comment]
This looks great. It would get us on more Cloud services faster.

**Comment by cjh1** [comment]
yes, it could be a nice migration path away from starcluster ...

**Comment by cjh1** [comment]
We decided to do the Ansible route
