### ISSUE TITLE
POST to /clusters endpoint says it requires 'template' where the doc says it's optional

### ISSUE THREAD

**Issue by TristanWright** [Kitware/cumulus#46]
By this: 
```
ClusterParameters {
  config{
    ssh {
      UserNameParameter {
        user (string, optional): The ssh user id
      }
    }
  },
  name (string): The name to give the cluster.,
  template (string, optional): The cluster template to use. (ec2 only),
  type (string): The cluster type, either "ec2" or "trad"
}
```
Sending only `name` and `type` should be ok?

**Comment by cjh1** [comment]
Yup , The documentation for this endpoint is a little screwed up ( there version of swagger we are using can't cope with the concept of 'one or another'. So here is a little explaination:

We have two type of cluster 'ec2' or 'trad'.

For 'ec2' the body should look like this:

```javascript
{
  "config" {
     "_id": " "
  },
  "name": "The name to give the cluster",
  "template": "The cluster template to use.",
  "type": "ec2"
}
```

for tradtional cluster ( this is the case you want I think ):

```javascript
{
  "config" {
     "ssh": {
       "user": "username"
  },
  "host": "thehost"
  "name": "The name to give the cluster",
  "type": "trad"
}
```

I hope that helps

**Comment by TristanWright** [comment]
aha, got it, _host_ goes in _config_ though.

**Comment by cjh1** [comment]
yep, I figured host was not specific the ssh.
