### ISSUE TITLE
Visualizer data-dir not always in ${HOME}

### ISSUE THREAD

**Issue by jourdain** [Kitware/cumulus#87]
This is specially true if jobOutputDir is defined.

We probably need to have the job templated with that information using ${HOME} if "jobOutputDir" is not defined.

**Comment by cjh1** [comment]
@jourdain Where are you seeing this? As far as I can tell we using the dataDir?

https://github.com/Kitware/cumulus/blob/master/scripts/pvw.sh#L34

**Comment by jourdain** [comment]
This is the generated pvw script.

DATA="5627ee1f0640fd2b836d70d8"
# If data directory is relative make it relative to $HOME
if [ "${DATA:0:1}" != "/" ]; then
DATA="${HOME}/${DATA}"
fi

**Comment by cjh1** [comment]
Looks like the wrong dataDir is being passed, it should be a full path ... I will take a look.

**Comment by cjh1** [comment]
Fixed
