### ISSUE TITLE
Provide finer grain task level status

### ISSUE THREAD

**Issue by cjh1** [Kitware/cumulus#92]
Current when the a task is in the running state the client has to query the task to work out what jobs it has and then listen for their status update. If we provided some sort of hierarchical state for example 'running.pvw.queued' then this might make things a little easier for clients of the API. Or alternative we could break out the state into two parts. For example have /tasks/<task_id>/status ('created', 'running', 'error', etc ) and /tasks/<task_id>/progress ('pvw.queued', 'pvw.error', etc. ). @TristanWright What do you think of this idea?

**Comment by TristanWright** [comment]
`running.pvw.queued` => `[task status].[task name].[job status]`?
That would be interesting.  What if there are two job statuses associated with the task?

**Comment by TristanWright** [comment]
> What if there are two job statuses associated with the task?
Only keep track of the latest job?

**Comment by cjh1** [comment]
That was my initial thought, however we could also provide a list of statuses. May be status could actually be object:

```
{
  "status": "running",
 "jobs": {
   "pvw": "running",
   "pvserver": "running"
 }
}

```

**Comment by cjh1** [comment]
This should be resolved by the taskflow code
