### ISSUE TITLE
#dollar-ref# for task log

### ISSUE THREAD

**Issue by TristanWright** [Kitware/cumulus#93]
![screen shot 2015-10-28 at 17 31 46](https://cloud.githubusercontent.com/assets/13318121/10806287/d4f82e9c-7d99-11e5-8c09-1ab38db915d3.png)

On a task tied to the meshtagger.

**Comment by cjh1** [comment]
How strange, I will look into it ...

**Comment by cjh1** [comment]
not sure how this can occur, are you able to recreate it?

**Comment by TristanWright** [comment]
Not since then, it only happened a handful of times that one afternoon. Can
probably close it.

On Fri, Oct 30, 2015 at 1:25 PM, Chris Harris <notifications@github.com>
wrote:

> not sure how this can occur, are you able to recreate it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Kitware/cumulus/issues/93#issuecomment-152624883>.
>



-- 
- Tristan Wright

*R&D Engineer*
*Kitware Inc.*

**Comment by cjh1** [comment]
We store $ref in mongo as #dollar-ref# as mongo doesn't like field that start with $. However, we replace them before sending them to the client. I am guessing there is a error path I can't see that prevents this replacement. Leave open for now ... If you see it any let me know.

**Comment by cjh1** [comment]
This is no longer relevant ....
